apiVersion: v1
kind: Service
metadata:
 name: adminer-srv
spec:
 selector:
  app: adminer
 ports:
  - name: adminer
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: adminer
 labels:
  app: adminer
spec:
 selector:
  matchLabels:
   app: adminer
 replicas: 1
 template:
  metadata:
   labels:
    app: adminer
  spec:
   containers:
    - name: adminer
      image: adminer
      resources:
       requests:
        memory: "64Mi"
        cpu: "0.125"
       limits:
        memory: "128Mi"
        cpu: "0.25"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: adminer-ingress
 annotations:
  dev.okteto.com/generate-host: "true"
spec:
 rules:
  - http:
     paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: adminer-srv
          port:
           number: 8080
