apiVersion: apps/v1
kind: Deployment
metadata:
 name: city-bikes-client-depl
spec:
 replicas: 2
 selector:
  matchLabels:
   app: city-bikes-client
 template:
  metadata:
   labels:
    app: city-bikes-client
  spec:
   containers:
    - name: city-bikes-client
      image: ginnyvt/city_bikes_react:1.0.0
      resources:
       requests:
        memory: "128Mi"
        cpu: "0.25"
       limits:
        memory: "256Mi"
        cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
 name: city-bikes-client-srv
spec:
 selector:
  app: city-bikes-client
 ports:
  - name: city-bikes-client
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 annotations:
  dev.okteto.com/generate-host: "true"
 name: city-bikes-client-ingress
spec:
 rules:
  - http:
     paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: city-bikes-client-srv
          port:
           number: 80
