apiVersion: apps/v1
kind: Deployment
metadata:
 name: city-bikes-server-depl
spec:
 replicas: 1
 selector:
  matchLabels:
   app: city-bikes-server
 template:
  metadata:
   labels:
    app: city-bikes-server
  spec:
   containers:
    - name: city-bikes-server
      image: ginnyvt/city_bikes_node:1.0.3
      envFrom:
       - secretRef:
          name: server-env
      resources:
       requests:
        memory: "128Mi"
        cpu: "0.25"
       limits:
        memory: "256Mi"
        cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
 name: city-bikes-server-srv
spec:
 selector:
  app: city-bikes-server
 ports:
  - name: city-bikes-server
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 annotations:
  dev.okteto.com/generate-host: "true"
 name: city-bikes-server-ingress
spec:
 rules:
  - http:
     paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: city-bikes-server-srv
          port:
           number: 3000
