version: "3.1"
services:
 db:
  container_name: mariadb
  image: mariadb:10.9
  restart: always
  env_file:
   - ./.env
  ports:
   - 3306:3306
  volumes:
   - ./db:/var/lib/mysql
   - ./../demo-data/output:/output
